/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_Crash
#define _Included_Crash
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jboolean JNICALL Java_Crash_getVersion(JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif
