/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Crash */

#ifndef _Included_Crash
#define _Included_Crash
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Crash
 * Method:    getVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Crash_getVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
