/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_Crash
#define _Included_Crash
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Test
 * Method:    isInterface
 * Signature: (Ljava/lang/Class;)Z
 */
JNIEXPORT jboolean JNICALL Java_Crash_isInterface
  (JNIEnv *, jobject, jclass);

#ifdef __cplusplus
}
#endif
#endif
